services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - frontend

  app:
    container_name: app
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - frontend
      - backend

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - backend

networks:
  frontend:
    name: frontend
  backend:
    name: backend
