services:
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./createTableAndInsert.sql:/docker-entrypoint-initdb.d/createTableAndInsert.sql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
